services:
  postgres:
    image: postgres:16-alpine
    container_name: ecomm-db
    environment:
      POSTGRES_DB: ecomm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: ecomm-auth
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/ecomm
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ecomm-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecomm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/ecomm-realm
    depends_on:
      - postgres
      - keycloak
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/pom.xml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ecomm-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/app
          target: /app/app
        - action: rebuild
          path: ./frontend/package.json

volumes:
  postgres_data:
