services:
  postgres:
    image: postgres:16-alpine
    container_name: ecomm-db
    environment:
      POSTGRES_DB: ecomm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ecomm"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: ecomm-auth
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/ecomm
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./infra/keycloak/realm-export.json:/opt/keycloak/data/import/realm.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ecomm-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecomm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/ecomm-realm/protocol/openid-connect/certs
      JWT_EXPECTED_ISSUER: http://localhost:8081/realms/ecomm-realm
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
        - action: rebuild
          path: ./backend/pom.xml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ecomm-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/package.json
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  postgres_data:
