/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductDetailsRouteImport } from './routes/products.$productId'
import { Route as BuyerIndexRouteImport } from './routes/buyer/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as RegisterRouteImport } from './routes/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)

const ProductDetailsRoute = ProductDetailsRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

const BuyerIndexRoute = BuyerIndexRouteImport.update({
  id: '/buyer/',
  path: '/buyer/',
  getParentRoute: () => rootRouteImport,
} as any)

const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/$productId': typeof ProductDetailsRoute
  '/buyer': typeof BuyerIndexRoute
  '/seller': typeof SellerIndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/': {
      id: '/buyer/'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof BuyerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

export const routeTree = rootRouteImport._addFileChildren({
  IndexRoute,
  ProductsIndexRoute,
  ProductDetailsRoute,
  BuyerIndexRoute,
  SellerIndexRoute,
  AdminIndexRoute,
  CheckoutRoute,
  RegisterRoute,
})
